### ISSUE TITLE
东西不错，感谢制作，能再完善完善吗

### ISSUE THREAD

**Issue by p4insh11** [techotaku/luci-app-transparent-proxy#1]
东西不错，感谢制作，能再完善完善吗，也许能更好
提出如下建议
分流设置，比如国内国外路由，支持CHNROUTER，自定义域名

**Comment by techotaku** [comment]
你可以参考 [Wiki](https://github.com/techotaku/luci-app-transparent-proxy/wiki/Get-Started)，China Route、自定义域名都有提到。

**Comment by p4insh11** [comment]
非常感谢
