### ISSUE TITLE
从哪里去找 v2ray (dokodemo)

### ISSUE THREAD

**Issue by yloveyy** [techotaku/luci-app-transparent-proxy#2]
我是直接从 v2ray 官方下载 linux 版的，配置好了之后从luci上看 提示 v2ray 未存在

**Comment by techotaku** [comment]
luci-app-transparent-proxy 只会检查v2ray进程是否在运行，如果下载的可执行文件叫别的名字可能检测不到。至于，dokodemo是v2ray的一个传入协议，按照v2ray官方文档配置即可。

**Comment by yloveyy** [comment]
@techotaku 感谢，已经手动启用了，另外 用这个 luci 配置是不是就不需要手动配置 iptables 了？

**Comment by techotaku** [comment]
嗯，这个工具的目的就是避免手动配置 iptables。“转发端口”、“额外被忽略IP”等没填错的话，“代理规则”在“存在”状态的时候就可以自动代理了。额外设置 黑/白 名单和 ChinaRoute 、DNS 防投毒的内容你可以参考 Wiki。

**Comment by yloveyy** [comment]
@techotaku 好的，谢谢！
