### ISSUE TITLE
开启后无法上网

### ISSUE THREAD

**Issue by hutozh** [techotaku/luci-app-transparent-proxy#3]
1、v2ray方案：ws+tls+nginx，手机、电脑正常使用。
2、路由器使用linux arm版本3.4，使用以下命令可以正常使用。路由器为lede最新版。
iptables -t nat -N V2RAY
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j V2RAY
3、透明代理里面能显示v2ray正常运行，但点击全局规则启用依然无法访问墙外网站。
4、v2ray error日志：
2018/01/02 07:16:52 [Warning]: App|DNS: failed to lookup IPs for domain play.google.com. > lookup play.google.com. on 192.168.1.1:53: read udp 192.168.1.14:45444->192.168.1.1:53: i/o timeout
2018/01/02 07:16:52 [Warning]: App|DNS: failed to lookup IPs for domain xxx.xxx. > lookup xxx.xxx. on 192.168.1.1:53: read udp 192.168.1.14:39845->192.168.1.1:53: i/o timeout
2018/01/02 07:16:52 [Warning]: App|DNS: failed to lookup IPs for domain xxx.xxx. > lookup xxx.xxx. on 192.168.1.1:53: read udp 192.168.1.14:39845->192.168.1.1:53: i/o timeout
2018/01/02 07:16:52 [Warning]: App|DNS: failed to lookup IPs for domain xxx.xxx. > lookup xxx.xxx. on 192.168.1.1:53: read udp 192.168.1.14:39845->192.168.1.1:53: i/o timeout
2018/01/02 07:16:53 [Warning]: App|DNS: failed to lookup IPs for domain clients3.google.com. > lookup clients3.google.com. on 192.168.1.1:53: read udp 192.168.1.14:43406->192.168.1.1:53: i/o timeout
2018/01/02 07:16:57 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37136->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: lookup xxx.xxx on 192.168.1.1:53: read udp 192.168.1.14:57424->192.168.1.1:53: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: operation was canceled] > Retry: all retry attempts failed
2018/01/02 07:16:58 [Warning]: App|DNS: failed to lookup IPs for domain plus.google.com. > lookup plus.google.com. on 192.168.1.1:53: read udp 192.168.1.14:42298->192.168.1.1:53: i/o timeout
2018/01/02 07:17:07 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37104->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37106->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: lookup xxx.xxx on 192.168.1.1:53: read udp 192.168.1.14:57424->192.168.1.1:53: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: lookup xxx.xxx on 192.168.1.1:53: dial udp 192.168.1.1:53: operation was canceled Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37152->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:17:15 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37110->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: lookup xxx.xxx on 192.168.1.1:53: read udp 192.168.1.14:57424->192.168.1.1:53: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: lookup xxx.xxx on 192.168.1.1:53: dial udp 192.168.1.1:53: operation was canceled Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37150->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37184->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:17:32 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: lookup xxx.xxx on 192.168.1.1:53: dial udp 192.168.1.1:53: operation was canceled Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37148->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37182->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37292->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37378->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:17:42 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37156->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37228->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37308->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37386->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37402->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:17:50 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37294->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37384->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37400->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37410->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: operation was canceled] > Retry: all retry attempts failed
2018/01/02 07:17:50 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37248->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37310->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37390->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37404->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37412->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:17:51 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37316->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37392->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37406->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37414->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: operation was canceled] > Retry: all retry attempts failed
2018/01/02 07:18:33 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37418->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37460->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37742->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37872->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37960->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:18:35 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37918->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37974->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: operation was canceled] > Retry: all retry attempts failed
2018/01/02 07:18:42 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37482->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37790->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37904->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37976->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38036->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:18:44 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37530->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37802->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37932->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37990->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38050->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:18:50 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37756->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37876->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:37958->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38034->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38104->xxx.xxx.xxx.xxx:443: i/o timeout] > Retry: all retry attempts failed
2018/01/02 07:19:11 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38312->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38358->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: operation was canceled] > Retry: all retry attempts failed
2018/01/02 07:19:15 [Warning]: failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38352->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > read tcp 192.168.1.14:38374->xxx.xxx.xxx.xxx:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://xxx.xxx/):  > dial tcp: operation was canceled] > Retry: all retry attempts failed

**Comment by hutozh** [comment]
有没有什么办法知道，开启规则后，有没有成功？

**Comment by techotaku** [comment]
@hutozh 看了一下你的log ，基本症状是连不上 V2Ray 服务器。你的服务器IP有没有填在“访问控制”的“额外被忽略IP”里面？

**Comment by techotaku** [comment]
开启以后，可以在“工作状态”-“代理规则”后面看到“存在”，这个时候查看系统防火墙，也会有“TP_SPEC_”的几个链。

**Comment by hutozh** [comment]
@techotaku 访问控制里暂时留空，什么也没填。
同时我路由器里按照这里：https://cokebar.info/archives/664，安装了ss,chinadns,dns转发。不知道会不会有影响？

**Comment by techotaku** [comment]
@hutozh DNS转发应该不要紧，但是 “额外被忽略IP” 是必填的……V2服务器IP需要填在这里。简单一点的解释是这里设定的规则会首先接管所有包的传输，然后按照访问控制来走，默认是都走代理，所以需要把服务器IP填在忽略里。你可以参考一下 [Get Started](https://github.com/techotaku/luci-app-transparent-proxy/wiki/Get-Started)。

**Comment by hutozh** [comment]
@techotaku 可以了，就是因为“额外被忽略IP”没填，是我没仔细看，你明明写着呢。
非常感谢你的帮助。有这个太方便了。

**Comment by techotaku** [comment]
没事，我回头把文档再整一下……

**Comment by hutozh** [comment]
不知道为什么，看youtube视频，要转很久很久才开始播放，打开网页速度还行。只用那三条iptabels命令也没问题。v2ray也没什么错误日志。

**Comment by techotaku** [comment]
可能是 udp 转发的问题，可以考虑关掉 udp 转发（关掉以后应该Chrome就能直接探测到 QUIC不可用 ）或者在 Chrome 禁用 QUIC。我也遇到过这个问题……在V2群里问过，大佬的答复是关掉 QUIC。Chrome对谷歌系的网站默认启用QUIC，会先发简单的udp包探测，这种简单的udp包是能被V2代理的（V2透明代理udp DNS或者 udp echo back也没问题我都试过了），但是后面承载数据的 udp 包貌似 V2处理起来有些问题。

**Comment by hutozh** [comment]
我再试试。配置界面的udp转发，和v2配置文件里的udp转发是一样的吗？是两个都要关掉吗？
另外听说chromecast或google home需要开udp转发，如果是这样的话，关udp也不行。。。

**Comment by techotaku** [comment]
@hutozh 配置里的 udp转发 去掉勾就行。chromecast或google home 没用过，不过你用 [这个帖子](https://toutyrater.github.io/app/transparent_proxy.html) 里如下 iptables 命令没问题的话，这边应该也没问题，因为他那边也没处理udp包……    
```
iptables -t nat -N V2RAY
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j V2RAY
```

**Comment by techotaku** [comment]
经过我实测是在如下的路径上 v2的udp转发（udp over tcp）会可能出问题：    
UDP客户端  >> iptables redirect to dokodemo >> [Router] V2Ray Client -> V2Ray TCP Outbound (tcp / ws) >> [Server] V2Ray Server TCP Inbound -> direct to Real UDP Server

**Comment by hutozh** [comment]
刚又测试了一下，关了luci的udp转发，配置文件里开启udp转发，目前正常使用。luci里udp转发开户，youtube就废了。

**Comment by hutozh** [comment]
另外想请教一下，如果这里和ss同时开启，那么上网会走哪呢？

**Comment by techotaku** [comment]
你是说ss的luci还是说只把ss-local跑起来？    
如果是ss的luci的话挺难说，看具体的iptables的执行顺序……    
如果只是把ss-local跑起来，你可以在我这个luci里面指定重定向的端口，重定向到v2的端口就走v2，重定向到ss的端口就走ss。我当时做这个就是有段时间有频繁切换v2/ss的需求……

**Comment by hutozh** [comment]
ss我是用的luci，就是不知道你这个和ss那个规则谁靠前了，现在我把ss关了。
还想请教一个问题，路由器里流量顺序是怎样的？手机/电脑发起连接，最先经过iptables还是dnsmasq，然后根据规则到达v2的dokodemo吗？

**Comment by flipphos** [comment]
@hutozh
能分享一下你的v2在 lede下的config文件吗？我之前试过dokodemo但是没有成功。想着v2和ss在不同端口双开，方便切换。多谢！

**Comment by hutozh** [comment]
@flipphos 按这里添加的：https://toutyrater.github.io/app/transparent_proxy.html
  "inbound": {
 "domainOverride":["tls","http"],
         "port":12345,
         "protocol":"dokodemo-door",
         "settings":{
             "network": "tcp,udp",
             "followRedirect": true,
			 "udp":true
         }
  },

**Comment by techotaku** [comment]
@hutozh 先过 iptables，符合规则的就会转发。一般 DNS 查询包会直接放行给 dnsmasq 的监听端口，因为大部分情况下查询你的网关（路由器本身的内网 IP），这个是不会转发给代理的。 dnsmasq 只做解析（如果开了 ipset 还会做 ipset 的标记），不会转发流量，起到一个域名免污染、国内加速或者GFW黑名单的作用（配合 chinadns 等），以及 ipset 分流标记的作用。

**Comment by hutozh** [comment]
@techotaku 是否可以这样理解，客户端访问，经过iptables，然后iptables如果没有相应转发规则，dns查询默认转给dnsmasq。这样的话，v2里面的dns模块就可以不用了。

**Comment by techotaku** [comment]
@hutozh 是的，路由器配好 chinadns 那一套的话，不需要v2来处理解析。v2的解析、路由分流这些，用在普通中转上很方便，在路由器上一般都已经有解决方案了。

**Comment by hutozh** [comment]
@techotaku 现在网络流程，我这么理解对吗？
1、在你这个luci设置了china列表，也就是dns解析完了，和这里匹配成功，直接走国内，不经v2。
2、如果匹配不成功，转发给v2，然后v2再用内置路由功能匹配一次，成功走freedom，否则走vmess。
2、网络流程：客户端↔DNSMASQ↔ chinadns→匹配直接走国内。
                                                                          ↓不匹配转到v2

**Comment by techotaku** [comment]
@hutozh 差不多就这样。

**Comment by hutozh** [comment]
@techotaku 真的感谢你的帮助，现在已经基本达到我想要的状态。dnsmasq+chinadns+v2ray。
v2ray程序删减模块后只有5.34M，v2配置文件只保留一个入站透明代理，一个出站vmess。

**Comment by techotaku** [comment]
@hutozh 不客气。
