### ISSUE TITLE
开启后无法自动翻越，国内网站似乎正常

### ISSUE THREAD

**Issue by sxjjw1987** [techotaku/luci-app-transparent-proxy#4]
v2ray配置文件如下
``{
  "log": {
    "access": "Vaccess.log",
    "error": "Verror.log",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 12345,
    "listen": "127.0.0.1",
    "protocol": "dokodemo-door",
    "settings": {
      "network": "tcp,udp",
      "followRedirect": true      
    }
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": " ",
          "port":  ,
          "users": [
            {
              "id": " ",
              "alterId": 64,
              "security": " "
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": ""
    },
    "mux": {
      "enabled": true
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "inboundDetour": [
    {
      "protocol": "socks",
      "port": 1080,
      "tag": "socks5",
      "listen": "0.0.0.0",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "192.168.1.1"
      }
    }
  ]
}

如题，配置按照https://github.com/techotaku/luci-app-transparent-proxy/wiki/Get-Started来的
设置同https://github.com/techotaku/luci-app-transparent-proxy/wiki/Screenshots
下面的ChinaList和GFWList也执行了

运行后，国内网站如淘宝京东等没问题，国外网站如Google等依旧打不开

这是哪里有什么问题吗
Linksys WRT1200AC，运行的最新的LEDE

**Comment by techotaku** [comment]
@sxjjw1987 V2ray的客户端和服务端日志有什么东西吗？

**Comment by sxjjw1987** [comment]
客户端是这样的：
`2018/02/11 14:57:06 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:12345
2018/02/11 14:57:06 [Debug]: App|Proxyman|Inbound: creating stream worker on 0.0.0.0:1080
2018/02/11 14:57:06 [Info]: Transport|Internet|TCP: listening TCP on 0.0.0.0:1080
2018/02/11 14:57:06 [Info]: Transport|Internet|UDP: listening UDP on 0.0.0.0:1080
2018/02/11 14:57:06 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:12345
2018/02/11 14:57:06 [Info]: Transport|Internet|UDP: listening UDP on 127.0.0.1:12345
2018/02/11 14:57:06 [Warning]: Core: V2Ray started
2018/02/11 13:47:22 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:12345
2018/02/11 13:47:22 [Debug]: App|Proxyman|Inbound: creating stream worker on 0.0.0.0:1080
2018/02/11 13:47:22 [Info]: Transport|Internet|TCP: listening TCP on 0.0.0.0:1080
2018/02/11 13:47:22 [Info]: Transport|Internet|UDP: listening UDP on 0.0.0.0:1080
2018/02/11 13:47:22 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:12345
2018/02/11 13:47:22 [Info]: Transport|Internet|UDP: listening UDP on 127.0.0.1:12345
2018/02/11 13:47:22 [Warning]: Core: V2Ray started`

服务端access日志太长了还有手机之类的访问记录，可能要清空一下才能贴出来

**Comment by sxjjw1987** [comment]
截取了一段服务器端在路由器重启前后的access.log信息
2018/02/12 08:41:10 220.200.59.120:36120 accepted tcp:149.154.175.50:80
2018/02/12 08:41:14 220.200.59.120:36123 accepted udp:8.8.8.8:53
2018/02/12 08:41:15 220.200.59.120:36132 accepted tcp:mtalk.google.com:5228
2018/02/12 08:41:16 220.200.59.120:36140 accepted udp:8.8.8.8:53
2018/02/12 08:41:18 220.200.59.120:36150 accepted udp:8.8.8.8:53
2018/02/12 08:41:19 220.200.59.120:36153 accepted tcp:alt1-mtalk.google.com:443
2018/02/12 08:41:43 220.200.59.120:36200 accepted tcp:149.154.175.50:80
2018/02/12 08:41:57 220.200.59.120:36246 accepted udp:8.8.8.8:53
2018/02/12 08:42:00 220.200.59.120:36257 accepted tcp:mtalk.google.com:5228
2018/02/12 08:42:09 220.200.59.120:36293 accepted udp:8.8.8.8:53
2018/02/12 08:42:12 220.200.59.120:36287 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 198.181.58.12:13166->220.200.59.120:36287: i/o timeout
2018/02/12 08:42:18 220.200.59.120:36315 accepted tcp:149.154.175.50:80
2018/02/12 08:42:36 220.200.59.120:36368 accepted udp:8.8.8.8:53
2018/02/12 08:42:38 220.200.59.120:36374 accepted tcp:mtalk.google.com:5228
2018/02/12 08:42:52 220.200.59.120:36414 accepted tcp:149.154.175.50:80
2018/02/12 08:43:15 220.200.59.120:36490 accepted udp:8.8.8.8:53
2018/02/12 08:43:16 220.200.59.120:36494 accepted tcp:mtalk.google.com:5228
2018/02/12 08:43:26 220.200.59.120:36527 accepted tcp:149.154.175.50:80

**Comment by sxjjw1987** [comment]
error.log如下，但是好像只记录了启动
2017/08/13 08:58:44 [Warning]Core: V2Ray started
2017/08/13 12:18:57 [Warning]Core: V2Ray started
2017/08/13 13:03:52 [Warning]Core: V2Ray started
2017/09/02 05:09:33 [Warning]Core: V2Ray started
2017/09/04 10:29:50 [Warning]Core: V2Ray started
2017/09/04 10:32:45 [Warning]Core: V2Ray started
2017/09/04 10:44:55 [Warning]Core: V2Ray started
2017/10/03 04:29:56 [Warning]Core: V2Ray started
2017/10/06 17:13:29 [Warning]Core: V2Ray started
2017/10/25 23:13:56 [Warning]Core: V2Ray started
2017/10/28 06:35:07 [Warning]Core: V2Ray started
2017/11/21 19:26:01 [Warning]Core: V2Ray started
2018/01/05 19:03:57 [Warning]Core: V2Ray started
2018/01/06 19:42:48 [Warning]Core: V2Ray started
2018/01/23 22:16:58 [Warning]Core: V2Ray started
2018/02/11 10:21:16 [Warning]: Core: V2Ray started
2018/02/11 10:22:51 [Warning]: Core: V2Ray started

**Comment by sxjjw1987** [comment]
还有就是，在打开Luci管理界面的时候发现浏览器底部显示在查询一个似乎是Kaspersky的地址
我的机器上有装卡巴死机，开启了网页防护

这是否表明目前的配置在国内地址解析上正常，但是国外地址的解析出现了问题？

**Comment by techotaku** [comment]
@sxjjw1987  不一定是解析的问题，也可能数据包根本没有转发过来。昨天忘了问，网站打不开具体报什么错？（最好用Chrome，报错比较清晰）是任意一个国外网站都打不开吗？    
另外，V2Ray是无状态的协议，因此抓服务器记录的时候最好是在没有其他客户端连接的时候看；或者至少要做到同一个外网地址下没有其他客户端（比如同一个路由器下只有这个路由器在连，手机等不要连），这个时候操作访问一下谷歌，然后看服务端有没有来自路由器公网IP的记录。    
回到上面你的这段log，`220.200.59.120` 是你路由器的公网IP吗？这个日志显示的这个时段还有其他客户端在连吗？

**Comment by sxjjw1987** [comment]
这个地址是我的路由器公网IP。同时段可能还有手机在连接。

我明天断开手机的连接再试一下。浏览器是FF，chrome，IE，EDGE混合着用。

**Comment by sxjjw1987** [comment]
2018/02/13 22:23:41 220.200.5.102:13836 accepted tcp:v1.mux.cool:9527

今天试了下，删除原有log，手机连接到另外的vps后打开路由尝试访问google，access.log里只有这么一条

chrome提示信息如下
无法访问此网站
www.google.com 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

另外还在路由器上尝试了一下curl google.com，倒是可以连上？

root@LEDE:~# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

**Comment by techotaku** [comment]
@sxjjw1987 过完年回来了……你的问题解决了吗……

**Comment by sxjjw1987** [comment]
还没有…放假完就出差了还没回家

都没空折腾

2018年2月27日 22:59，"Ian Li" <notifications@github.com>写道：

**Comment by techotaku** [comment]
@sxjjw1987  我稍微总结一下，你回去试一试：    
症状是国外网站打不开；客户端服务端都没有报错。    
这种我感觉，DNS的问题、或者 国外网站的数据包根本没有转发过来 的可能性比较大。    

对 DNS 问题，你把 8.8.8.8 加到“强制走代理IP”里面，然后DNS改8.8.8.8试试；    
排除数据包转发问题的话，你在配置里加一个inboundDetour，配成 socks5，然后局域网用socks5连一下看看能不能用。

**Comment by sxjjw1987** [comment]
好的

顺便请教下，按照正常来讲，如果同样配置下ss可用，那么用v2ray替换ss，transparent proxy替换ss的luci
app，对应设置完端口后应该也行
大体上是这样吗

2018年2月27日 23:13，"Ian Li" <notifications@github.com>写道：

@sxjjw1987 <https://github.com/sxjjw1987> 我稍微总结一下，你回去试一试：
症状是国外网站打不开；客户端服务端都没有报错。
这种我感觉，DNS的问题、或者 国外网站的数据包根本没有转发过来 的可能性比较大。

对 DNS 问题，你把 8.8.8.8 加到“强制走代理IP”里面，然后DNS改8.8.8.8试试；
排除数据包转发问题的话，你在配置里加一个inboundDetour，配成 socks5，然后局域网用socks5连一下看看能不能用。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/techotaku/luci-app-transparent-proxy/issues/4#issuecomment-368910774>,
or mute the thread

**Comment by techotaku** [comment]
对……我这个基本上就是从SS那个LuCI里拆出来的……
