### ISSUE TITLE
额外被忽略IP选项能否增加域名支持

### ISSUE THREAD

**Issue by clswang** [techotaku/luci-app-transparent-proxy#5]
在额为被忽略ip选项输入域名的时候，提示值无效，无法保存。

**Comment by techotaku** [comment]
这个地方用来填写代理服务器的IP。    
如果有域名直连分流的需求，请参考 [Wiki - Get Started](https://github.com/techotaku/luci-app-transparent-proxy/wiki/Get-Started#china-list) 通过  dnsmasq + ipset 解决：    
    
```
server=/synology.com/119.29.29.29
ipset=/synology.com/tp_spec_dst_bp
server=/transmissionbt.com/119.29.29.29
ipset=/transmissionbt.com/tp_spec_dst_bp
```

**Comment by clswang** [comment]
v2ray的服务器只有域名而没有ip该如何设置，谢谢

**Comment by techotaku** [comment]
@clswang 如果是动态IP，就比较愁人了……除了写脚本定时解析、更新配置，我这边暂时想不到什么别的办法……

**Comment by techotaku** [comment]
可能是我之前没说清楚：    
如果只有域名没有IP，填不了 额外忽略IP，可以把域名写入 tp_spec_dst_bp 的 ipset，效果应该一样。
